language: python
sudo: required
dist: trusty
install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - pip install Pygments
    
# Build the website
script:
    - cd public && git checkout master && cd ..
    - hugo

after_success: |
    if [ -n "$GITHUB_API_KEY" ]; then
        echo -e "\033[0;32mDeploying updates to GitHub...\033[0m"
        cd public
        git add .
        msg="rebuilding site `date`" 
        if [ $# -eq 1 ]
            then msg="$1"
        fi
        echo -e "git commit, m:$msg"
        git -c user.name='Qi Ma' -c user.email='mq@tuojie.com' commit -m "$msg"
        git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/qima/qima.github.io.git master
    fi  