language: python
sudo: required
dist: trusty
group: deprecated-2017Q4
install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - pip install Pygments
    
# Build the website
script:
  - hugo

after_success: |
    if [ -n "$GITHUB_API_KEY" ]; then
    echo -e "\033[0;32mDeploying updates to GitHub...\033[0m"
    cd public
    git add .
    msg="重新构建站点 `date`" 
    if [ $# -eq 1 ]
    then msg="$1"
    fi
    git checkout master
    echo -e "\033[0;32mgit commit, m:$msg \033[0m"
    git -c user.name='Qi Ma' -c user.email='mq@tuojie.com' commit -m "$msg"
    echo -e "\033[0;32m提交消息为$msg \033[0m"    
    git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/qima/qima.github.io.git master
    git status
    fi  